version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # location of your requirements.txt
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: "security-updates"
        update-types:
          - "security"
